### ISSUE TITLE
UberStar Open Only to Several Universities?

### ISSUE THREAD

**Issue by mercury04G** [codicate/underclassmen-internships#44]
https://www.uber.com/us/en/careers/list/?query=uberstar 
When I searched for UberStar on their job posting website, it only gave me roles for certain universities. Is it open to all sophomores across the country? Thanks.

**Comment by codicate** [comment]
Hi I'm also not sure about why this is. I found a reddit thread about this: https://www.reddit.com/r/csMajors/comments/177vmeh/uberstar/

I hope they open a posting for all university soon
